import { useMutation, useQuery } from '@tanstack/react-query';
import { useNavigate } from 'react-router-dom';
import { api, unwrap, type Schemas } from '../../api/client';
import { ErrorBox, Loading, PageHeader } from '../../components/ui';
import { ModuleIcon } from '../../components/icons';
import { titleCase } from '../../lib/format';
import { speechSupported } from '../../lib/speech';

type StartBody = Schemas['ListeningStartRequest'];

const PARTS = [
  'Everyday conversation, two speakers',
  'Everyday monologue (tour, talk, radio)',
  'Academic discussion, up to four speakers',
  'Academic lecture',
];

export function ListeningHome() {
  const navigate = useNavigate();
  const sections = useQuery({
    queryKey: ['listening', 'sections'],
    queryFn: () => unwrap(api.GET('/api/listening/sections')),
  });
  const start = useMutation({
    mutationFn: (body: StartBody) => unwrap(api.POST('/api/listening/sessions', { body })),
    onSuccess: (s) => navigate(`/listening/session/${s.sessionId}`),
  });
  return (
    <div className="page">
      <PageHeader
        eyebrow="Listening"
        title="Hear it once. Answer like it counts."
        subtitle="Four parts, 40 questions, reading time before each part and 10 minutes to transfer answers. Voices are generated by your browser with a different accent for each speaker."
        icon={<ModuleIcon module="LISTENING" size={28} />}
      />
      {!speechSupported() && (
        <div className="alert alert-warn">
          This browser has no speech synthesis — use a recent Chrome, Edge or Safari.
        </div>
      )}
      <ErrorBox error={start.error} title="Could not start" />
      <div className="grid grid-3">
        <div className="card card-hover stack">
          <h3>Full test — exam mode</h3>
          <p className="muted small">
            Audio plays once, straight through all four parts, then the transfer-time countdown auto-submits.
          </p>
          <button
            className="btn"
            disabled={start.isPending}
            onClick={() => start.mutate({ mode: 'EXAM', scope: 'TEST' })}
          >
            Start exam
          </button>
        </div>
        <div className="card card-hover stack">
          <h3>Full test — practice mode</h3>
          <p className="muted small">
            Pause, replay any part, skip reading time. Replays are recorded with your answers.
          </p>
          <button
            className="btn btn-secondary"
            disabled={start.isPending}
            onClick={() => start.mutate({ mode: 'PRACTICE', scope: 'TEST' })}
          >
            Start practice
          </button>
        </div>
        <div className="card card-hover stack">
          <h3>Single part</h3>
          <div className="stack" style={{ gap: '0.4rem' }}>
            {PARTS.map((label, i) => (
              <button
                key={label}
                className="btn btn-secondary btn-sm"
                style={{ justifyContent: 'flex-start' }}
                disabled={start.isPending}
                onClick={() => start.mutate({ mode: 'PRACTICE', scope: 'SECTION', section: i + 1 })}
              >
                Part {i + 1} · <span className="muted">{label}</span>
              </button>
            ))}
          </div>
        </div>
      </div>
      <div className="card" style={{ marginTop: '1rem' }}>
        <div className="card-title">
          <h2>Recording bank</h2>
        </div>
        {sections.isLoading && <Loading />}
        <div className="stack" style={{ gap: 0 }}>
          {sections.data?.map((s) => (
            <div key={s.id} className="list-row">
              <div style={{ minWidth: 0 }}>
                <div className="truncate">
                  <span className="badge badge-primary">Part {s.section}</span> {s.title}
                </div>
                <div className="small muted">
                  {(s.questionTypes ?? '')
                    .split(',')
                    .filter(Boolean)
                    .map((t) => titleCase(t))
                    .join(' · ')}{' '}
                  · used {s.timesServed}×
                </div>
              </div>
              <button
                className="btn btn-ghost btn-sm"
                onClick={() => start.mutate({ mode: 'PRACTICE', scope: 'SECTION', itemId: s.id })}
              >
                Practise
              </button>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
