/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['me'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['changePassword'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/reading/passages': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['passages'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/reading/sessions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['start'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/reading/sessions/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['session'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/reading/sessions/{id}/result': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['result'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/reading/sessions/{id}/submit': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['submit'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/system/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['health'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/system/spend': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['spend'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/system/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['status'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ChangePasswordRequest: {
      currentPassword: string;
      newPassword: string;
    };
    DiagramEdge: {
      from: string;
      label: string;
      to: string;
    };
    DiagramNode: {
      id: string;
      label: string;
      /** Format: double */
      x: number;
      /** Format: double */
      y: number;
    };
    DiagramSpec: {
      edges: components['schemas']['DiagramEdge'][];
      nodes: components['schemas']['DiagramNode'][];
      title: string;
    };
    /** @default null */
    FlaggedWordRequest: {
      /** Format: int64 */
      itemId?: number;
      sentence?: string;
      word?: string;
    };
    Health: {
      status: string;
    };
    InventoryRow: {
      /** Format: int64 */
      count: number;
      module: string;
      status: string;
      taskType: string;
    };
    LoginRequest: {
      email: string;
      password: string;
    };
    MapFeature: {
      /** Format: double */
      h: number;
      kind: string;
      label: string;
      /** Format: double */
      w: number;
      /** Format: double */
      x: number;
      /** Format: double */
      y: number;
    };
    MapMarker: {
      key: string;
      /** Format: double */
      x: number;
      /** Format: double */
      y: number;
    };
    MapSpec: {
      features: components['schemas']['MapFeature'][];
      markers: components['schemas']['MapMarker'][];
      title: string;
    };
    Me: {
      email: string;
      role: string;
    };
    Paragraph: {
      label: string;
      text: string;
    };
    Question: {
      answers: string[];
      justification_span: string;
      location: string;
      /** Format: int32 */
      number: number;
      options: components['schemas']['QuestionOption'][];
      prompt: string;
    };
    QuestionGroup: {
      choice: boolean;
      context: string;
      diagram: components['schemas']['DiagramSpec'];
      flow_steps: string[];
      group_id: string;
      instructions: string;
      map: components['schemas']['MapSpec'];
      number_allowed: boolean;
      options: components['schemas']['QuestionOption'][];
      /** @enum {string} */
      question_type:
        | 'MULTIPLE_CHOICE'
        | 'MULTIPLE_CHOICE_MULTI'
        | 'TRUE_FALSE_NOT_GIVEN'
        | 'YES_NO_NOT_GIVEN'
        | 'MATCHING_INFORMATION'
        | 'MATCHING_HEADINGS'
        | 'MATCHING_FEATURES'
        | 'MATCHING_SENTENCE_ENDINGS'
        | 'SENTENCE_COMPLETION'
        | 'SUMMARY_COMPLETION'
        | 'NOTE_COMPLETION'
        | 'TABLE_COMPLETION'
        | 'FLOW_CHART_COMPLETION'
        | 'DIAGRAM_LABEL_COMPLETION'
        | 'SHORT_ANSWER'
        | 'FORM_COMPLETION'
        | 'MAP_LABELLING'
        | 'MATCHING';
      questions: components['schemas']['Question'][];
      table: components['schemas']['TableSpec'];
      /** Format: int32 */
      word_limit: number;
    };
    QuestionOption: {
      key: string;
      text: string;
    };
    QuestionResult: {
      blank: boolean;
      correct: boolean;
      expected: string[];
      given: string;
      group_id: string;
      justification: string;
      location: string;
      /** @default  */
      note: string | null;
      /** Format: int32 */
      number: number;
      /** @enum {string} */
      question_type:
        | 'MULTIPLE_CHOICE'
        | 'MULTIPLE_CHOICE_MULTI'
        | 'TRUE_FALSE_NOT_GIVEN'
        | 'YES_NO_NOT_GIVEN'
        | 'MATCHING_INFORMATION'
        | 'MATCHING_HEADINGS'
        | 'MATCHING_FEATURES'
        | 'MATCHING_SENTENCE_ENDINGS'
        | 'SENTENCE_COMPLETION'
        | 'SUMMARY_COMPLETION'
        | 'NOTE_COMPLETION'
        | 'TABLE_COMPLETION'
        | 'FLOW_CHART_COMPLETION'
        | 'DIAGRAM_LABEL_COMPLETION'
        | 'SHORT_ANSWER'
        | 'FORM_COMPLETION'
        | 'MAP_LABELLING'
        | 'MATCHING';
    };
    ReadingPassage: {
      cefr: string;
      /** Format: int32 */
      difficulty: number;
      paragraphs: components['schemas']['Paragraph'][];
      question_groups: components['schemas']['QuestionGroup'][];
      title: string;
      topic: string;
    };
    /** @default null */
    ReadingPassageResult: {
      /** Format: int64 */
      attemptId: number;
      /** Format: int64 */
      itemId: number;
      /** Format: int32 */
      max: number;
      /** Format: int32 */
      numberOffset: number;
      questions: components['schemas']['QuestionResult'][];
      /** Format: int32 */
      raw: number;
      /**
       * Format: int32
       * @default
       */
      secondsSpent: number | null;
      title: string;
    };
    /** @default null */
    ReadingPassageSummary: {
      /** @default  */
      cefr: string | null;
      /**
       * Format: int32
       * @default
       */
      difficulty: number | null;
      /** Format: int64 */
      id: number;
      origin: string;
      /** @default  */
      questionTypes: string | null;
      /** @default  */
      sourceUrl: string | null;
      /** Format: int32 */
      timesServed: number;
      title: string;
      /** @default  */
      topic: string | null;
    };
    /** @default null */
    ReadingPassageView: {
      /** Format: int64 */
      itemId: number;
      /** @default  */
      licence: string | null;
      /** Format: int32 */
      numberOffset: number;
      passage: components['schemas']['ReadingPassage'];
      /** Format: int32 */
      questionCount: number;
      /** @default  */
      sourceUrl: string | null;
    };
    /** @default null */
    ReadingResultView: {
      /** Format: double */
      band: number;
      bandIsEstimate: boolean;
      /** Format: int32 */
      blanks: number;
      /** @enum {string} */
      kind:
        | 'READING_TEST'
        | 'READING_PASSAGE'
        | 'LISTENING_TEST'
        | 'LISTENING_SECTION'
        | 'WRITING_TASK1'
        | 'WRITING_TASK2'
        | 'WRITING_TEST'
        | 'SPEAKING_TEST'
        | 'SPEAKING_PART'
        | 'GRAMMAR_DIAGNOSTIC'
        | 'GRAMMAR_EXERCISE'
        | 'GRAMMAR_ERROR_DRILL'
        | 'VOCAB_REVIEW';
      /** Format: int32 */
      maxScore: number;
      /** @enum {string} */
      mode: 'PRACTICE' | 'EXAM';
      passageTexts: components['schemas']['ReadingPassageView'][];
      passages: components['schemas']['ReadingPassageResult'][];
      /** Format: int32 */
      rawScore: number;
      /** Format: int64 */
      sessionId: number;
      /** Format: date-time */
      submittedAt: string;
      /**
       * Format: int32
       * @default
       */
      timeLimitSeconds: number | null;
      /**
       * Format: int32
       * @default
       */
      timeUsedSeconds: number | null;
    };
    /** @default null */
    ReadingSessionView: {
      /** @enum {string} */
      kind:
        | 'READING_TEST'
        | 'READING_PASSAGE'
        | 'LISTENING_TEST'
        | 'LISTENING_SECTION'
        | 'WRITING_TASK1'
        | 'WRITING_TASK2'
        | 'WRITING_TEST'
        | 'SPEAKING_TEST'
        | 'SPEAKING_PART'
        | 'GRAMMAR_DIAGNOSTIC'
        | 'GRAMMAR_EXERCISE'
        | 'GRAMMAR_ERROR_DRILL'
        | 'VOCAB_REVIEW';
      /** @enum {string} */
      mode: 'PRACTICE' | 'EXAM';
      passages: components['schemas']['ReadingPassageView'][];
      /** Format: int64 */
      sessionId: number;
      /** Format: date-time */
      startedAt: string;
      status: string;
      /**
       * Format: int32
       * @default
       */
      timeLimitSeconds: number | null;
    };
    /** @default null */
    ReadingStartRequest: {
      /** Format: int32 */
      difficulty?: number;
      /** Format: int64 */
      itemId?: number;
      /** @enum {string} */
      mode: 'PRACTICE' | 'EXAM';
      /**
       * @default null
       * @enum {string}
       */
      scope: 'TEST' | 'PASSAGE';
    };
    /** @default null */
    ReadingSubmitRequest: {
      answers?: {
        [key: string]: string;
      };
      flaggedWords?: components['schemas']['FlaggedWordRequest'][];
      secondsPerPassage?: {
        [key: string]: number;
      };
      /** Format: int32 */
      timeUsedSeconds?: number;
    };
    /** @default null */
    SpendStatus: {
      apiKeyConfigured: boolean;
      backgroundLimit: number;
      backgroundPaused: boolean;
      /** Format: int64 */
      callsToday: number;
      capReached: boolean;
      dailyCap: number;
      spentLast7Days: number;
      spentToday: number;
    };
    SystemStatus: {
      apiKeyConfigured: boolean;
      inventory: components['schemas']['InventoryRow'][];
      models: {
        [key: string]: string;
      };
      spend: components['schemas']['SpendStatus'];
    };
    TableSpec: {
      columns: string[];
      rows: string[][];
      title: string;
    };
    TokenResponse: {
      email: string;
      /** Format: date-time */
      expiresAt: string;
      role: string;
      token: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenResponse'];
        };
      };
    };
  };
  me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Me'];
        };
      };
    };
  };
  changePassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ChangePasswordRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  passages: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReadingPassageSummary'][];
        };
      };
    };
  };
  start: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ReadingStartRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReadingSessionView'];
        };
      };
    };
  };
  session: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReadingSessionView'];
        };
      };
    };
  };
  result: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReadingResultView'];
        };
      };
    };
  };
  submit: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ReadingSubmitRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReadingResultView'];
        };
      };
    };
  };
  health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Health'];
        };
      };
    };
  };
  spend: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SpendStatus'];
        };
      };
    };
  };
  status: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SystemStatus'];
        };
      };
    };
  };
}
